### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zocom-david-lundholm** [cenglander/e-wallet#1]
Bra jobbat Charlotte!

Buggar:
* Du kan inte välja kortet längst fram som active card

Tänk på:
* När du passar *relaterad data* mellan olika delar i JavaScript är det oftast mest effektivt att kapsla in det i objekt och skicka objektet istället för att skicka varje parameter för sig. I det här fallet datan du skickar till Card-komponenten, istället för att ha en prop för varje datapunkt i kortet, ha *en* prop för hela kortobjektet. Det är en princip som alltid är värd att följa; 

```
Skriv kod så att om en förändring skulle ske så behöver du ändra så lite som möjligt.
```

Om du skulle byta namn på/ta bort/lägga till någon datapunkt på dina kortobjekt så skulle du också behöva justera koden på varje ställe som du mountar Card-komponenten.

**Comment by cenglander** [comment]
Tack!
Buggen är nu fixad.
Tack, jag förstår. Det är en del jag skulle vilja göra om och lägga till i den här uppgiften nu. Har börjat lite med formulärvalidering och att kunna klicka ner det valda kortet igen t.ex.
